name: "Setup Environment"
description: "Checkout repository and setup Node.js with pnpm"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 9
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"
    - name: Install dependencies
      run: pnpm install
      shell: bash
