name: "Run Tests"
description: "Run linting and tests"

runs:
  using: "composite"
  steps:
    - name: Lint
      run: pnpm lint
      shell: bash
    - name: Test
      run: pnpm test
      shell: bash
